# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: paper_analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'paper_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14paper_analysis.proto\x12\rpaperanalysis\"H\n\x0e\x41nalyzeRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x11\n\tpaper_url\x18\x02 \x01(\t\x12\x13\n\x0bpaper_title\x18\x03 \x01(\t\"6\n\nKeyFinding\x12\x0f\n\x07\x66inding\x18\x01 \x01(\t\x12\x17\n\x0frelevance_score\x18\x02 \x01(\x02\"\xa4\x01\n\x0f\x41nalyzeResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12/\n\x0ckey_findings\x18\x04 \x03(\x0b\x32\x19.paperanalysis.KeyFinding\x12\x18\n\x10\x63onfidence_score\x18\x05 \x01(\x02\x12\x15\n\rerror_message\x18\x06 \x01(\t2e\n\x14PaperAnalysisService\x12M\n\x0c\x41nalyzePaper\x12\x1d.paperanalysis.AnalyzeRequest\x1a\x1e.paperanalysis.AnalyzeResponseB=Z;github.com/AvinashSaxena777/papermind/mcp-tool-server/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paper_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/AvinashSaxena777/papermind/mcp-tool-server/proto'
  _globals['_ANALYZEREQUEST']._serialized_start=39
  _globals['_ANALYZEREQUEST']._serialized_end=111
  _globals['_KEYFINDING']._serialized_start=113
  _globals['_KEYFINDING']._serialized_end=167
  _globals['_ANALYZERESPONSE']._serialized_start=170
  _globals['_ANALYZERESPONSE']._serialized_end=334
  _globals['_PAPERANALYSISSERVICE']._serialized_start=336
  _globals['_PAPERANALYSISSERVICE']._serialized_end=437
# @@protoc_insertion_point(module_scope)
