// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: paper_analysis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//-----Request---------
type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	PaperUrl      string                 `protobuf:"bytes,2,opt,name=paper_url,json=paperUrl,proto3" json:"paper_url,omitempty"`
	PaperTitle    string                 `protobuf:"bytes,3,opt,name=paper_title,json=paperTitle,proto3" json:"paper_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_paper_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_paper_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AnalyzeRequest) GetPaperUrl() string {
	if x != nil {
		return x.PaperUrl
	}
	return ""
}

func (x *AnalyzeRequest) GetPaperTitle() string {
	if x != nil {
		return x.PaperTitle
	}
	return ""
}

type KeyFinding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Finding        string                 `protobuf:"bytes,1,opt,name=finding,proto3" json:"finding,omitempty"`
	RelevanceScore float32                `protobuf:"fixed32,2,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyFinding) Reset() {
	*x = KeyFinding{}
	mi := &file_paper_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyFinding) ProtoMessage() {}

func (x *KeyFinding) ProtoReflect() protoreflect.Message {
	mi := &file_paper_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyFinding.ProtoReflect.Descriptor instead.
func (*KeyFinding) Descriptor() ([]byte, []int) {
	return file_paper_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *KeyFinding) GetFinding() string {
	if x != nil {
		return x.Finding
	}
	return ""
}

func (x *KeyFinding) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

type AnalyzeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Summary         string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	KeyFindings     []*KeyFinding          `protobuf:"bytes,4,rep,name=key_findings,json=keyFindings,proto3" json:"key_findings,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_paper_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paper_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_paper_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AnalyzeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalyzeResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalyzeResponse) GetKeyFindings() []*KeyFinding {
	if x != nil {
		return x.KeyFindings
	}
	return nil
}

func (x *AnalyzeResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *AnalyzeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_paper_analysis_proto protoreflect.FileDescriptor

const file_paper_analysis_proto_rawDesc = "" +
	"\n" +
	"\x14paper_analysis.proto\x12\rpaperanalysis\"e\n" +
	"\x0eAnalyzeRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tpaper_url\x18\x02 \x01(\tR\bpaperUrl\x12\x1f\n" +
	"\vpaper_title\x18\x03 \x01(\tR\n" +
	"paperTitle\"O\n" +
	"\n" +
	"KeyFinding\x12\x18\n" +
	"\afinding\x18\x01 \x01(\tR\afinding\x12'\n" +
	"\x0frelevance_score\x18\x02 \x01(\x02R\x0erelevanceScore\"\xe8\x01\n" +
	"\x0fAnalyzeResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12<\n" +
	"\fkey_findings\x18\x04 \x03(\v2\x19.paperanalysis.KeyFindingR\vkeyFindings\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x02R\x0fconfidenceScore\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage2e\n" +
	"\x14PaperAnalysisService\x12M\n" +
	"\fAnalyzePaper\x12\x1d.paperanalysis.AnalyzeRequest\x1a\x1e.paperanalysis.AnalyzeResponseB=Z;github.com/AvinashSaxena777/papermind/mcp-tool-server/protob\x06proto3"

var (
	file_paper_analysis_proto_rawDescOnce sync.Once
	file_paper_analysis_proto_rawDescData []byte
)

func file_paper_analysis_proto_rawDescGZIP() []byte {
	file_paper_analysis_proto_rawDescOnce.Do(func() {
		file_paper_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paper_analysis_proto_rawDesc), len(file_paper_analysis_proto_rawDesc)))
	})
	return file_paper_analysis_proto_rawDescData
}

var file_paper_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_paper_analysis_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: paperanalysis.AnalyzeRequest
	(*KeyFinding)(nil),      // 1: paperanalysis.KeyFinding
	(*AnalyzeResponse)(nil), // 2: paperanalysis.AnalyzeResponse
}
var file_paper_analysis_proto_depIdxs = []int32{
	1, // 0: paperanalysis.AnalyzeResponse.key_findings:type_name -> paperanalysis.KeyFinding
	0, // 1: paperanalysis.PaperAnalysisService.AnalyzePaper:input_type -> paperanalysis.AnalyzeRequest
	2, // 2: paperanalysis.PaperAnalysisService.AnalyzePaper:output_type -> paperanalysis.AnalyzeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_paper_analysis_proto_init() }
func file_paper_analysis_proto_init() {
	if File_paper_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paper_analysis_proto_rawDesc), len(file_paper_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paper_analysis_proto_goTypes,
		DependencyIndexes: file_paper_analysis_proto_depIdxs,
		MessageInfos:      file_paper_analysis_proto_msgTypes,
	}.Build()
	File_paper_analysis_proto = out.File
	file_paper_analysis_proto_goTypes = nil
	file_paper_analysis_proto_depIdxs = nil
}
