// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: paper_analysis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaperAnalysisService_AnalyzePaper_FullMethodName = "/paperanalysis.PaperAnalysisService/AnalyzePaper"
)

// PaperAnalysisServiceClient is the client API for PaperAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------Service--------
type PaperAnalysisServiceClient interface {
	AnalyzePaper(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type paperAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaperAnalysisServiceClient(cc grpc.ClientConnInterface) PaperAnalysisServiceClient {
	return &paperAnalysisServiceClient{cc}
}

func (c *paperAnalysisServiceClient) AnalyzePaper(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, PaperAnalysisService_AnalyzePaper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaperAnalysisServiceServer is the server API for PaperAnalysisService service.
// All implementations must embed UnimplementedPaperAnalysisServiceServer
// for forward compatibility.
//
// ------Service--------
type PaperAnalysisServiceServer interface {
	AnalyzePaper(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedPaperAnalysisServiceServer()
}

// UnimplementedPaperAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaperAnalysisServiceServer struct{}

func (UnimplementedPaperAnalysisServiceServer) AnalyzePaper(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzePaper not implemented")
}
func (UnimplementedPaperAnalysisServiceServer) mustEmbedUnimplementedPaperAnalysisServiceServer() {}
func (UnimplementedPaperAnalysisServiceServer) testEmbeddedByValue()                              {}

// UnsafePaperAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaperAnalysisServiceServer will
// result in compilation errors.
type UnsafePaperAnalysisServiceServer interface {
	mustEmbedUnimplementedPaperAnalysisServiceServer()
}

func RegisterPaperAnalysisServiceServer(s grpc.ServiceRegistrar, srv PaperAnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedPaperAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaperAnalysisService_ServiceDesc, srv)
}

func _PaperAnalysisService_AnalyzePaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperAnalysisServiceServer).AnalyzePaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaperAnalysisService_AnalyzePaper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperAnalysisServiceServer).AnalyzePaper(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaperAnalysisService_ServiceDesc is the grpc.ServiceDesc for PaperAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaperAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paperanalysis.PaperAnalysisService",
	HandlerType: (*PaperAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzePaper",
			Handler:    _PaperAnalysisService_AnalyzePaper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paper_analysis.proto",
}
